### ISSUE TITLE
Issues while running the example

### ISSUE THREAD

**Issue by ggthedev** [JV17/JVMenuPopover#2]
Hi,
I was trying your control and have found following issues in different simulator settings:
setting: iOS 8.2
Issue: "2015-04-30 19:20:04.820 JVMenuPopover[62622:2018211] is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.
"

setting: iOS 7.1
Issue: application crashes moment i tap the menu button with following message
"
dyld: lazy symbol binding failed: Symbol not found: _UIAccessibilityIsReduceTransparencyEnabled
Referenced from: /Users/gauravgupta/Library/Developer/CoreSimulator/Devices/6688E8A4-A011-47FB-8093-D7DF9A6CC39F/data/Applications/808FDF95-4C4D-415B-959B-910FF0AC55F8/JVMenuPopover.app/JVMenuPopover
Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit

dyld: Symbol not found: _UIAccessibilityIsReduceTransparencyEnabled
Referenced from: /Users/gauravgupta/Library/Developer/CoreSimulator/Devices/6688E8A4-A011-47FB-8093-D7DF9A6CC39F/data/Applications/808FDF95-4C4D-415B-959B-910FF0AC55F8/JVMenuPopover.app/JVMenuPopover
Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
"

can u let me know if there is any solution or your control was meant only for iOS 8+? If so, any idea what i can try to make it work for iOS 7

**Comment by JV17** [comment]
@gaurav1981, 
The issue regarding iOS 8.2 animating its opacity is an annoying warning from Apple that suggests the opacity should be 1 because you could not have the desire effect that you want, but indeed we have them. So, there is not much to do there... 

I have fixed the issues in iOS 7 but you won't get the same effect as iOS8 since this has been completely develop using some of the new technologies in the iOS 8 SDK.
