### ISSUE TITLE
Landscape/Portrait orientation?

### ISSUE THREAD

**Issue by Stan92** [JV17/JVMenuPopover#3]
Hi,
Thanks for sharing this controller.
I notice there's a little problem if the app uses orientation when the menu is displayed..

By the way, is it possible to use a tableview for the menu?
If I have a lot menu items, it seems I can't scroll the menu...

**Comment by JV17** [comment]
@Stan92 Sorry for the late reply. I'm currently working on the orientation issue. Also, the many items issue is done but will be release when the orientation issue is fixed.

If you want to fix the many items in the menu. You could go and change the lazy initialization of the tableview and remove the flags on the **JVMenuPopoverView.m** to **YES**,

`_tableView.bounces = YES;`
`_tableView.scrollEnabled = YES;`

This issue is currently on development under [ISSUE 6](https://github.com/JV17/JVMenuPopover/issues/6).

Cheers!
